### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by kbuwel** [nomadkaraoke/python-audio-separator#131]
I am using a conda virtual environment.
I used pip install "audio-separator[gpu for the first run.
I entered audio-separator a.wav --model_filename model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt
and started downloading the model.
The problem was that it worked with cpu, not gpu.
conda install pytorch=*=*cuda* onnxruntime=*=*cuda* audio-separator -c pytorch -c conda-forge
The installation was completed and the following error was displayed.
Traceback (most recent call last):

File "C:\ProgramData\anaconda3\envs\audio\Scripts\audio-separator-script.py", line 9, in <module>

sys.exit(main())

File "C:\ProgramData\anaconda3\envs\audio\lib\site-packages\audio_separator\utils\cli.py", line 122, in main from audio_separator.separator import Separator File "C:\ProgramData\anaconda3\envs\audio\lib\site-packages\audio_separator\separator\__init__.py", line 1, in <module > from . separator import Separator File "C:\ProgramData\anaconda3\envs\audio\lib\site-packages\audio_separator\separator\separator.py", line 15, in <modu le> import yaml ModuleNotFoundError: No module named 'yaml'

**Comment by beveradb** [comment]
Sorry, I don't have enough info to know what has happened here - it seems like you're missing a dependency but I don't know how.

What is `audio-separator-script.py`?

Can you provide more detail, e.g. what version of Python, what version of audio-separator do you have, what dependencies exist in your environment, etc.?

I also have no way to test on Windows myself so can only provide limited support - it's probably a Windows problem 😅

**Comment by beveradb** [comment]
Closing as user provided no detail, no errors, logs or steps to reproduce the issue.
Feel free to reopen if you want to provide some detail on what exactly didn't work, what you tried, etc.
