### ISSUE TITLE
[Bug]: using specific model in docker not working

### ISSUE THREAD

**Issue by acimail01** [nomadkaraoke/python-audio-separator#147]
#### download model to host folder
docker run --rm -it -v ${PWD}:/workdir beveradb/audio-separator --model_file_dir "./tmp/audio-separator/h" --model_filename htdemucs_6s.yaml --download_model_only

#### using model from folder
docker run --rm -it -v ${PWD}:/workdir beveradb/audio-separator --model_file_dir "./tmp/audio-separator/h" --model_filename htdemucs_6s.yaml mysong.mp3

Model download works, but separation command fails.
The audio separation does not work.

### Have you searched for existing issues?  🔎

- [X] I have searched and found no existing issues.

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/bin/audio-separator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audio_separator/utils/cli.py", line 208, in main
    output_files = separator.separate(audio_file, primary_output_name=args.primary_output_name, secondary_output_name=args.secondary_output_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/audio_separator/separator/separator.py", line 774, in separate
    output_files = self.model_instance.separate(audio_file_path, primary_output_name, secondary_output_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### System Info

```shell
Operating System: 
Python version: 
Other...
```

**Comment by beveradb** [comment]
Closing as there was no detail to work with - no logs, no reproducible example or error message etc.
If you'd like this to be investigated, please provide more detail and try and look into it yourself first.
