### ISSUE TITLE
[Bug]: Some models configs are not found error 404

### ISSUE THREAD

**Issue by Eddycrack864** [nomadkaraoke/python-audio-separator#171]
### Describe the bug

The config file for some models cannot be found, response code 404.

The affected models are:
* MelBand Roformer Kim | Inst V1 by Unwa (This model works, because it uses the same configuration file as the Inst V1 (E))
* MelBand Roformer Kim | Inst V2 by Unwa
* MelBand Roformer Kim | InstVoc Duality V1 by Unwa
* MelBand Roformer Kim | InstVoc Duality V2 by Unwa

I think they moved/deleted the configuration file from where it was before. As a quick fix, we could upload the configuration files and maybe the checkpoints as well to the audio-separator models repo.

### Have you searched for existing issues?  🔎

- [X] I have searched and found no existing issues.

### Logs

```shell
Traceback (most recent call last):
File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 570, in download_model_files
self.download_file_if_not_exists(yaml_url, download_path)
File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 345, in download_file_if_not_exists
raise RuntimeError(f"Failed to download file from {url}, response code: {response.status_code}")
RuntimeError: Failed to download file from https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/mdx_model_data/mdx_c_configs/config_melbandroformer_inst_v2.yaml, response code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\AIStuffCDrive\UVR5-UI\app.py", line 247, in roformer_separator
separator.load_model(model_filename=roformer_model)
File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 672, in load_model
model_filename, model_type, model_friendly_name, model_path, yaml_config_filename = self.download_model_files(model_filename)
File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 574, in download_model_files
self.download_file_if_not_exists(yaml_url, download_path)
File "C:\AIStuffCDrive\UVR5-UI\env\lib\site-packages\audio_separator\separator\separator.py", line 345, in download_file_if_not_exists
raise RuntimeError(f"Failed to download file from {url}, response code: {response.status_code}")
RuntimeError: Failed to download file from https://github.com/nomadkaraoke/python-audio-separator/releases/download/model-configs/config_melbandroformer_inst_v2.yaml, response code: 404
```

### System Info

```shell
Operating System: Apply to all OS
Python version: Apply to all versions
Other...
```

**Comment by Eddycrack864** [comment]
The config files are here: https://github.com/TRvlvr/application_data/tree/main/mdx_model_data/mdx_c_configs

**Comment by beveradb** [comment]
Oh wow, sorry about that - thanks for catching it! Fixed.
