### ISSUE TITLE
"CUDA_PATH is set but CUDA wasnt able to be loaded" error despite successful --env_info test

### ISSUE THREAD

**Issue by jet082** [nomadkaraoke/python-audio-separator#70]
Using CUDA 12.4, ``audio-separator[gpu]``, and onnxruntime-gpu 1.18.0 installed via ``pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/``

``audio-separator.exe --env_info`` renders the following:
```
2024-05-21 08:30:45,876 - INFO - separator - Separator version 0.16.6 instantiating with output_dir: None, output_format: WAV
2024-05-21 08:30:45,877 - INFO - separator - Operating System: Windows 10.0.22635
2024-05-21 08:30:45,895 - INFO - separator - System: Windows Node: Irrelevant Release: 11 Machine: AMD64 Proc: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
2024-05-21 08:30:45,896 - INFO - separator - Python Version: 3.12.3
2024-05-21 08:30:45,896 - INFO - separator - PyTorch Version: 2.3.0+cu121
2024-05-21 08:30:45,989 - INFO - separator - FFmpeg installed: ffmpeg version N-113449-g2887bd4a03-ge0da916b8f+4 Copyright (c) 2000-2024 the FFmpeg developers
2024-05-21 08:30:45,991 - INFO - separator - ONNX Runtime GPU package installed with version: 1.18.0
2024-05-21 08:30:45,992 - INFO - separator - ONNX Runtime CPU package installed with version: 1.18.0
2024-05-21 08:30:46,011 - INFO - separator - CUDA is available in Torch, setting Torch device to CUDA
2024-05-21 08:30:46,011 - INFO - separator - ONNXruntime has CUDAExecutionProvider available, enabling acceleration
```

However, simply running ``audio-separator.exe .\03.wav --model_filename UVR-MDX-NET-Inst_HQ_3.onnx`` presents the error
```
2024-05-21 08:33:14.740 - INFO - cli - Separator version 0.16.6 beginning with input file: .\03.wav
2024-05-21 08:33:14.742 - INFO - separator - Separator version 0.16.6 instantiating with output_dir: None, output_format: FLAC
2024-05-21 08:33:14.743 - INFO - separator - Operating System: Windows 10.0.22635
2024-05-21 08:33:14.767 - INFO - separator - System: Windows Node: Irrelevant Release: 11 Machine: AMD64 Proc: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
2024-05-21 08:33:14.767 - INFO - separator - Python Version: 3.12.3
2024-05-21 08:33:14.767 - INFO - separator - PyTorch Version: 2.3.0+cu121
2024-05-21 08:33:14.887 - INFO - separator - FFmpeg installed: ffmpeg version N-113449-g2887bd4a03-ge0da916b8f+4 Copyright (c) 2000-2024 the FFmpeg developers
2024-05-21 08:33:14.890 - INFO - separator - ONNX Runtime GPU package installed with version: 1.18.0
2024-05-21 08:33:14.895 - INFO - separator - ONNX Runtime CPU package installed with version: 1.18.0
2024-05-21 08:33:14.950 - INFO - separator - CUDA is available in Torch, setting Torch device to CUDA
2024-05-21 08:33:14.951 - INFO - separator - ONNXruntime has CUDAExecutionProvider available, enabling acceleration
2024-05-21 08:33:14.951 - INFO - separator - Loading model UVR-MDX-NET-Inst_HQ_3.onnx...
2024-05-21 08:33:19.6050196 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*************** EP Error ***************
EP Error C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-05-21 08:33:19.9259898 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 onnxruntime::TryGetProviderInfo_CUDA] C:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Scripts\audio-separator.exe\__main__.py", line 7, in <module>
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\utils\cli.py", line 175, in main
    separator.load_model(model_filename=args.model_filename)
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\separator\separator.py", line 644, in load_model
    self.model_instance = separator_class(common_config=common_params, arch_config=self.arch_specific_params[model_type])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 95, in __init__
    self.load_model()
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 122, in load_model
    ort_inference_session = ort.InferenceSession(self.model_path, providers=self.onnx_execution_provider, sess_options=ort_session_options)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise fallback_error from e
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 427, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\Users\jet082\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  make sure they're in the PATH, and that your GPU is supported.
```

**Comment by beveradb** [comment]
Hey, so I don't have a windows machine or an nvidia GPU to test with those, but the error message you're getting:

`RuntimeError: C:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:866 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded.`

`Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page`  (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements),  `make sure they're in the PATH, and that your GPU is supported.`

 comes from ONNX Runtime - and it does give you a strong nudge towards some actions; have you tried reading through the page it links to and trying to install the right versions of CUDA and cuDNN?

This issue seems like someone else having a similar issue on windows: https://github.com/microsoft/onnxruntime/issues/11826

And, the reason this only occurs with the MDX models (not MDXC, VR or Demucs) is that ONNX Runtime is only used in the MDX class: https://github.com/karaokenerds/python-audio-separator/blob/main/audio_separator/separator/architectures/mdx_separator.py

but not in e.g. the MDXC class: https://github.com/karaokenerds/python-audio-separator/blob/main/audio_separator/separator/architectures/mdxc_separator.py

different model architectures have pretty different code paths once the separation is instantiated - hope that makes sense! 😄

**Comment by darkzbaron** [comment]
works for me too!
