### ISSUE TITLE
ValueError: Unsupported Model File: parameters for MD5 hash dac7f142d5adf52ee84c1e900a3c2725 could not be found in UVR model data file for MDX or VR arc

### ISSUE THREAD

**Issue by Lixi20** [nomadkaraoke/python-audio-separator#85]
(myenv) PS D:\AIDownloads\DS测试工具\音轨分离> audio-separator D:\AIDownloads\DS测试工具\测试音频\玫瑰的故事E02_1.mp3 --output_format=mp3 --single_stem=Vocals --sample_rate=44100 --demucs_shifts=4 --demucs_overlap=0.25 --model_filename 955717e8-8726e21a.th --output_dir D:\AIDownloads\DS测试工具\测试音频\out
2024-07-12 10:55:19.793 - INFO - cli - Separator version 0.17.5 beginning with input file: D:\AIDownloads\DS测试工具\测试音频\玫瑰的故事E02_1.mp3
2024-07-12 10:55:19.794 - INFO - separator - Separator version 0.17.5 instantiating with output_dir: D:\AIDownloads\DS测试工具\测试音频\out, output_format: mp3
2024-07-12 10:55:19.794 - INFO - separator - Operating System: Windows 10.0.22631
2024-07-12 10:55:19.794 - INFO - separator - System: Windows Node: Geek Release: 10 Machine: AMD64 Proc: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
2024-07-12 10:55:19.794 - INFO - separator - Python Version: 3.10.6
2024-07-12 10:55:19.794 - INFO - separator - PyTorch Version: 2.3.1+cpu
2024-07-12 10:55:19.808 - INFO - separator - FFmpeg installed: ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
2024-07-12 10:55:19.809 - INFO - separator - ONNX Runtime GPU package installed with version: 1.18.1
2024-07-12 10:55:19.809 - INFO - separator - No hardware acceleration could be configured, running in CPU mode
2024-07-12 10:55:19.809 - INFO - separator - Loading model 955717e8-8726e21a.th...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 84.1M/84.1M [05:21<00:00, 262kiB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21.0/21.0 [00:00<?, ?iB/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AIDownloads\DS测试工具\音轨分离\myenv\Scripts\audio-separator.exe\__main__.py", line 7, in <module>
  File "D:\AIDownloads\DS测试工具\音轨分离\myenv\lib\site-packages\audio_separator\utils\cli.py", line 175, in main
    separator.load_model(model_filename=args.model_filename)
  File "D:\AIDownloads\DS测试工具\音轨分离\myenv\lib\site-packages\audio_separator\separator\separator.py", line 641, in load_model
    model_data = self.load_model_data_using_hash(model_path)
  File "D:\AIDownloads\DS测试工具\音轨分离\myenv\lib\site-packages\audio_separator\separator\separator.py", line 615, in load_model_data_using_hash
    raise ValueError(f"Unsupported Model File: parameters for MD5 hash {model_hash} could not be found in UVR model data file for MDX or VR arch.")
ValueError: Unsupported Model File: parameters for MD5 hash dac7f142d5adf52ee84c1e900a3c2725 could not be found in UVR model data file for MDX or VR arc

**Comment by Lixi20** [comment]
audio-separator        0.17.5

**Comment by beveradb** [comment]
Ah, sorry this isn't super clear with the demucs models but you need to specify the model file name rather than one of the partial filenames

So, instead of `--model_filename 955717e8-8726e21a.th` you would use `--model_filename htdemucs.yaml`

Hope that helps!
