### ISSUE TITLE
AttributeError: 'VRSeparator' object has no attribute 'arch_name'

### ISSUE THREAD

**Issue by Lixi20** [nomadkaraoke/python-audio-separator#86]
**audio-separator        0.17.5**

(myenv) PS D:\AIDownloads\DS测试工具\音轨分离> audio-separator D:\AIDownloads\DS测试工具\测试音频\玫瑰的故事E02_1.mp3 --output_format=mp3 --vr_window_size=320 --vr_aggression=10 --single_stem=Vocals --sample_rate=44100 --model_filename UVR-De-Echo-Normal.pth --vr_batch_size=16 --vr_window_size=320 --output_dir D:\AIDownloads\DS测试工具\测试音频\out
2024-07-12 14:25:21.776 - INFO - cli - Separator version 0.17.5 beginning with input file: D:\AIDownloads\DS测试工具\测试音频\玫瑰的故事E02_1.mp3
2024-07-12 14:25:21.777 - INFO - separator - Separator version 0.17.5 instantiating with output_dir: D:\AIDownloads\DS测试工具\测试音频\out, output_format: mp3
2024-07-12 14:25:21.778 - INFO - separator - Operating System: Windows 10.0.22631
2024-07-12 14:25:21.778 - INFO - separator - System: Windows Node: Geek Release: 10 Machine: AMD64 Proc: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
2024-07-12 14:25:21.778 - INFO - separator - Python Version: 3.10.6
2024-07-12 14:25:21.778 - INFO - separator - PyTorch Version: 2.3.1+cpu
2024-07-12 14:25:21.792 - INFO - separator - FFmpeg installed: ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
2024-07-12 14:25:21.793 - INFO - separator - ONNX Runtime GPU package installed with version: 1.18.1
2024-07-12 14:25:21.793 - INFO - separator - No hardware acceleration could be configured, running in CPU mode
2024-07-12 14:25:21.793 - INFO - separator - Loading model UVR-De-Echo-Normal.pth...
2024-07-12 14:25:22.029 - INFO - vr_separator - VR Separator initialisation complete
2024-07-12 14:25:22.029 - INFO - separator - Load model duration: 00:00:00
2024-07-12 14:25:22.029 - INFO - separator - Starting separation process for audio_file_path: D:\AIDownloads\DS测试工具\测试音频\玫瑰的故事E02_1.mp3
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.57it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:00<00:00, 57044.94it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:43<00:00, 10.91s/it]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AIDownloads\DS测试工具\音轨分离\myenv\Scripts\audio-separator.exe\__main__.py", line 7, in <module>
  File "D:\AIDownloads\DS测试工具\音轨分离\myenv\lib\site-packages\audio_separator\utils\cli.py", line 177, in main
    output_files = separator.separate(args.audio_file)
  File "D:\AIDownloads\DS测试工具\音轨分离\myenv\lib\site-packages\audio_separator\separator\separator.py", line 704, in separate
    output_files = self.model_instance.separate(audio_file_path)
  File "D:\AIDownloads\DS测试工具\音轨分离\myenv\lib\site-packages\audio_separator\separator\architectures\vr_separator.py", line 184, in separate
    self.logger.warning(f"The output_single_stem setting '{self.output_single_stem}' does not match any of the output files: '{self.primary_stem_name}' and '{self.secondary_stem_name}'. For this model '{self.model_name}' with architecture '{self.arch_name}', the output_single_stem setting will be ignored and all output files will be saved.")
AttributeError: 'VRSeparator' object has no attribute 'arch_name'

**Comment by beveradb** [comment]
Hey, thanks for the report! That was a very silly bug. 

[Fixed](https://github.com/nomadkaraoke/python-audio-separator/commit/8b0d9b02b72b2c3aaddb743a0401b2a0772aa360) in version `0.18`+
